// client.c
// Generated by decompiling client.exe
// using Reko decompiler version 0.7.1.0.

#include "client.h"

// 0041100A: Register Eq_2 fn0041100A(Stack (ptr wchar_t) ptrArg04, Stack Eq_4 tArg08, Stack (ptr wchar_t) ptrArg0C, Stack (ptr wchar_t) ptrArg10, Stack (ptr wchar_t) ptrArg14, Stack (ptr wchar_t) ptrArg18)
errno_t fn0041100A(wchar_t * ptrArg04, size_t tArg08, wchar_t * ptrArg0C, wchar_t * ptrArg10, wchar_t * ptrArg14, wchar_t * ptrArg18)
{
	return _wmakepath_s(ptrArg04, tArg08, ptrArg0C, ptrArg10, ptrArg14, ptrArg18);
}

// 0041101E: void fn0041101E()
void fn0041101E()
{
	return;
}

// 00411023: void fn00411023()
void fn00411023()
{
	return;
}

// 00411037: void fn00411037()
void fn00411037()
{
	fn004143F0();
	return;
}

// 00411055: Register Eq_2 fn00411055(Stack (ptr wchar_t) ptrArg04, Stack Eq_23 tArg08, Stack (ptr wchar_t) ptrArg0C)
errno_t fn00411055(wchar_t * ptrArg04, rsize_t tArg08, wchar_t * ptrArg0C)
{
	return wcscpy_s(ptrArg04, tArg08, ptrArg0C);
}

// 0041105A: void fn0041105A(Stack (ptr char) ptrArg04, Stack Eq_23 tArg08, Stack (ptr char) ptrArg0C)
void fn0041105A(char * ptrArg04, rsize_t tArg08, char * ptrArg0C)
{
	strcpy_s(ptrArg04, tArg08, ptrArg0C);
	return;
}

// 00411064: void fn00411064(Stack (ptr char) ptrArg04, Stack Eq_23 tArg08, Stack (ptr char) ptrArg0C)
void fn00411064(char * ptrArg04, rsize_t tArg08, char * ptrArg0C)
{
	strcat_s(ptrArg04, tArg08, ptrArg0C);
	return;
}

// 0041106E: void fn0041106E(Register word32 eax, Register word32 ecx, Register Eq_51 edx, Register word32 ebx, Register ptr32 ebp, Register word32 esi, Register Eq_55 edi, Register (ptr Eq_56) es, Register (ptr Eq_57) ds)
void fn0041106E(word32 eax, word32 ecx, Eq_51 edx, word32 ebx, ptr32 ebp, word32 esi, Eq_55 edi, Eq_56 * es, Eq_57 * ds)
{
	fn00411348();
	if (eax == 0x00)
	{
		*(fp - 0x0338) = 0x03;
		fn00411037();
		*(fp - 0x033C) = 0x02CC;
		*(fp - 0x0340) = 0x00;
		*(fp - 0x0344) = fp - 0x0330;
		*(fp - 0x0280) = fn004110CD(ptrArg00, dwArg04, tArg08);
		*(fp - 644) = ecx;
		*(fp - 0x0288) = (union Eq_51 *) edx;
		*(fp - 0x028C) = ebx;
		*(fp - 656) = esi;
		*(fp - 660) = (union Eq_55 *) edi;
		*(fp - 616) = (struct Eq_131 **) ss;
		*(fp - 0x0274) = (struct Eq_137 **) cs;
		*(fp - 664) = (struct Eq_57 **) ds;
		*(fp - 668) = (struct Eq_56 **) es;
		*(fp - 0x02A0) = (struct Eq_153 **) fs;
		*(fp - 676) = (struct Eq_159 **) gs;
		*(fp - 0x033C) = (union Eq_167 *) cond(fp - 0x0338);
		*(fp - 0x0270) = *(fp - 0x033C);
		*(fp - 0x0330) = 0x00010001;
		*(fp - 0x0278) = fp->dw0000;
		*(fp - 0x026C) = (struct Eq_64 **) fp;
		*(fp - 636) = *(fp - 0x04);
		*(fp - 0x033C) = 0x50;
		*(fp - 0x0340) = 0x00;
		*(fp - 0x0344) = fp - 100;
		fn004110CD(ptrArg00, dwArg04, tArg08);
		*(fp - 100) = 0x40000015;
		*(fp - 0x60) = 0x01;
		*(fp - 88) = fp->dw0000;
		if (IsDebuggerPresent() == 0x01)
			*(fp - 0x05) = 0x01;
		else
			*(fp - 0x05) = 0x00;
		*(fp - 0x06) = *(fp - 0x05);
		*(fp - 0x14) = fp - 100;
		*(fp - 0x10) = fp - 0x0330;
		*(fp - 0x033C) = 0x00;
		SetUnhandledExceptionFilter(*(fp - 0x033C));
		*(fp - 0x033C) = fp - 0x14;
		*(fp - 0x0C) = (int32) UnhandledExceptionFilter(*(fp - 0x033C));
		if (*(fp - 0x0C) == 0x00 && (word32) (*(fp - 0x06)) == 0x00)
		{
			*(fp - 0x033C) = 0x03;
			fn00411037();
		}
		return;
	}
	else
		__fastfail(fp->dw0004);
}

// 00411073: Register word32 fn00411073()
word32 fn00411073()
{
	word32 dwLoc08_12;
	if (globals->dw41A030 != 0x00)
		dwLoc08_12 = 0x01;
	else
		dwLoc08_12 = 0x00;
	return dwLoc08_12;
}

// 0041107D: void fn0041107D()
void fn0041107D()
{
	word32 * edi_17 = fp - 0xC4;
	word32 ecx_18 = 0x30;
	while (ecx_18 != 0x00)
	{
		*edi_17 = 0xCCCCCCCC;
		edi_17 = edi_17 + 0x01;
		ecx_18 = ecx_18 - 0x01;
	}
	return;
}

// 00411082: Register word32 fn00411082()
word32 fn00411082()
{
	return fs->dw0018;
}

// 004110A0: void fn004110A0()
void fn004110A0()
{
	word32 esp_2;
	initterm_e();
	return;
}

// 004110B9: void fn004110B9()
void fn004110B9()
{
	word32 esp_2;
	cexit();
	return;
}

// 004110C8: Register word32 fn004110C8()
word32 fn004110C8()
{
	return globals->dw41A510;
}

// 004110CD: Register (ptr void) fn004110CD(Stack (ptr void) ptrArg04, Stack int32 dwArg08, Stack Eq_4 tArg0C)
void(void, int32 dwArg08, size_t tArg0C)
{
	return memset(ptrArg04, dwArg08, tArg0C);
}

// 004110D2: void fn004110D2()
void fn004110D2()
{
	word32 esp_2;
	get_initial_wide_environment();
	return;
}

// 004110E1: Register ptr32 fn004110E1()
ptr32 fn004110E1()
{
	return 4302204;
}

// 004110F5: void fn004110F5(Register Eq_51 edx, Register (ptr Eq_407) ebx, Register Eq_51 esi, Register Eq_55 edi, Register (ptr Eq_56) es, Register (ptr Eq_57) ds)
void fn004110F5(Eq_51 edx, Eq_407 * ebx, Eq_51 esi, Eq_55 edi, Eq_56 * es, Eq_57 * ds)
{
	fn00412AC0(edx, ebx, esi, edi, es, ds, dwArg00, dwArg04);
	return;
}

// 00411136: void fn00411136(Register Eq_51 edx, Register word32 ebx, Register Eq_55 edi, Register (ptr Eq_56) es, Register (ptr Eq_57) ds)
void fn00411136(Eq_51 edx, word32 ebx, Eq_55 edi, Eq_56 * es, Eq_57 * ds)
{
	globals->dw41A570 = 0x00;
	ui32 eax_18 = globals->dw41A02C;
	globals->dw41A02C = eax_18 | 0x01;
	fn00411348();
	if ((eax_18 | 0x01) != 0x00)
	{
		*(fp - 0x14) = 0x00;
		*(fp - 0x10) = 0x00;
		*(fp - 0x0C) = 0x00;
		globals->dw41A570 = 0x01;
		globals->dw41A02C = globals->dw41A02C | 0x02;
		word32 eax_68;
		word32 ebx_69;
		word32 ecx_70;
		word32 edx_71;
		__cpuid(0x00, 0x00, &eax_68, &ebx_69, &ecx_70, &edx_71);
		*(fp - 0x24) = eax_68;
		*(fp - 0x20) = ebx_69;
		*(fp - 0x1C) = ecx_70;
		*(fp - 0x18) = edx_71;
		*(fp - 0x34) = *(fp - 0x24);
		if ((*(fp - 0x20) ^ 1970169159 | *(fp - 0x18) ^ 0x49656E69 | *(fp - 0x1C) ^ 1818588270) == 0x00)
			*(fp - 0x30) = 0x01;
		else
			*(fp - 0x30) = 0x00;
		*(fp - 0x25) = *(fp - 0x30);
		word32 eax_103;
		word32 ebx_104;
		word32 ecx_105;
		word32 edx_106;
		__cpuid(0x01, 0x00, &eax_103, &ebx_104, &ecx_105, &edx_106);
		*(fp - 0x24) = eax_103;
		*(fp - 0x20) = ebx_104;
		*(fp - 0x1C) = ecx_105;
		*(fp - 0x18) = edx_106;
		*(fp - 44) = *(fp - 0x24);
		if ((word32) *(fp - 0x25) != 0x00 && ((*(fp - 44) & 0x0FFF3FF0) == 0x000106C0 || ((*(fp - 44) & 0x0FFF3FF0) == 0x00020660 || ((*(fp - 44) & 0x0FFF3FF0) == 0x00020670 || ((*(fp - 44) & 0x0FFF3FF0) == 0x00030650 || ((*(fp - 44) & 0x0FFF3FF0) == 0x00030660 || (*(fp - 44) & 0x0FFF3FF0) == 0x00030670))))))
			globals->dw41A574 = globals->dw41A574 | 0x01;
		*(fp - 0x14) = *(fp - 0x18);
		*(fp - 0x10) = *(fp - 0x1C);
		if (*(fp - 0x34) >= 0x07)
		{
			word32 eax_218;
			word32 ebx_219;
			word32 ecx_220;
			word32 edx_221;
			__cpuid(0x07, 0x00, &eax_218, &ebx_219, &ecx_220, &edx_221);
			*(fp - 0x24) = eax_218;
			*(fp - 0x20) = ebx_219;
			*(fp - 0x1C) = ecx_220;
			*(fp - 0x18) = edx_221;
			*(fp - 0x0C) = *(fp - 0x20);
			if ((*(fp - 0x20) & 0x0200) != 0x00)
				globals->dw41A574 = globals->dw41A574 | 0x02;
		}
		ui32 edx_142 = *(fp - 0x10);
		edx = edx_142 & 0x00100000;
		if ((edx_142 & 0x00100000) != 0x00)
		{
			globals->dw41A570 = 0x02;
			globals->dw41A02C = globals->dw41A02C | 0x04;
			ui32 edx_164 = *(fp - 0x10);
			edx = edx_164 & 0x08000000;
			if ((edx_164 & 0x08000000) != 0x00 && (*(fp - 0x10) & 0x10000000) != 0x00)
			{
				word32 edx_181 = SLICE(__xgetbv(0x00), word32, 32);
				*(fp - 0x3C) = 0x04;
				*(fp - 0x38) = edx_181;
				ui32 edx_184 = *(fp - 0x3C);
				ui32 eax_185 = *(fp - 0x38);
				*(fp - 0x44) = edx_184 & 0x06;
				*(fp - 0x40) = eax_185 & 0x00;
				edx = edx_184 & 0x06;
				if (*(fp - 0x44) == 0x06 && *(fp - 0x40) == 0x00)
				{
					globals->dw41A570 = 0x03;
					globals->dw41A02C = globals->dw41A02C | 0x08;
					edx.u0 = 0x08;
					if ((*(fp - 0x0C) & 0x20) != 0x00)
					{
						globals->dw41A570 = 0x05;
						globals->dw41A02C = globals->dw41A02C | 0x20;
					}
				}
			}
		}
	}
	fn004112B2(0x00, *(fp - 0x08) ^ fp - 0x04, edx, *(fp - 0x4C), *(fp - 0x50), edi, es, ds);
	return;
}

// 0041113B: void fn0041113B()
void fn0041113B()
{
	fn00412230();
	return;
}

// 00411145: Register byte fn00411145()
byte fn00411145()
{
	byte al_20;
	Eq_254 eax_9 = GetModuleHandleW(null);
	if (eax_9 == 0x00)
		al_20 = 0x00;
	else if ((word32) *eax_9 != 23117)
		al_20 = 0x00;
	else
	{
		word32 eax_46 = eax_9 + Mem0[eax_9 + 0x3C:word32];
		if (eax_46->unused != 0x4550)
			al_20 = 0x00;
		else if ((word32) eax_46->dw0018 != 0x010B)
			al_20 = 0x00;
		else if (eax_46->t0074 <= 0x0E)
			al_20 = 0x00;
		else if (eax_46->dw00E8 == 0x00)
			al_20 = 0x00;
		else
			al_20 = 0x01;
	}
	return al_20;
}

// 00411154: Register word32 fn00411154(Register ptr32 ebp, Register (ptr Eq_56) es, Register (ptr Eq_57) ds, Stack int32 dwArg04, Stack (ptr Eq_968) dwArg08)
word32 fn00411154(ptr32 ebp, Eq_56 * es, Eq_57 * ds, int32 dwArg04, Eq_968 * dwArg08)
{
	struct Eq_969 * esp_14 = fp - 0x06BC;
	word32 * edi_17 = fp - 0x06B0;
	word32 ecx_18 = 0x01AB;
	while (ecx_18 != 0x00)
	{
		*edi_17 = 0xCCCCCCCC;
		edi_17 = edi_17 + 0x01;
		ecx_18 = ecx_18 - 0x01;
	}
	ui32 eax_27 = globals->dw41A000 ^ fp - 0x04;
	Eq_984 dwLoc1C_29 = &globals->v417B30;
	if (dwArg04 > 0x01)
		dwLoc1C_29 = dwArg08->t0004;
l00411A1A:
	ptr32 esp_159;
	Eq_51 edx_153;
	ui32 eax_160;
	struct Eq_56 * es_155;
	struct Eq_57 * ds_156;
	if (0x01 != 0x00)
	{
		struct Eq_969 * esp_624 = esp_14 - 0x04;
		esp_624->t0000 = null;
		*(esp_624 - 0x04) = 0x00;
		*(esp_624 - 0x08) = 0x03;
		*(esp_624 - 0x0C) = 0x00;
		*(esp_624 - 0x10) = 0x00;
		*(esp_624 - 0x14) = 0xC0000000;
		*(esp_624 - 0x18) = 4291448;
		Eq_1029 eax_639 = CreateFileW(*(esp_624 - 0x18), *(esp_624 - 0x14), *(esp_624 - 0x10), *(esp_624 - 0x0C), *(esp_624 - 0x08), *(esp_624 - 0x04), esp_624->t0000);
		fn0041113B();
		esp_14 = esp_624;
		dwLoc10 = eax_639;
		if (eax_639 == (void *) ~0x00)
		{
			Eq_254 eax_647 = GetLastError();
			fn0041113B();
			if (eax_647 != 0xE7)
			{
				Eq_254 eax_653 = GetLastError();
				fn0041113B();
				esp_624->tFFFFFFF4 = eax_653;
				esp_624->dwFFFFFFF0 = 4291500;
				word32 edx_660;
				word32 eax_661 = fn004112BC(out edx_660);
				esp_624->dwFFFFFFF0 = 0x01;
				ptr32 esp_669;
				word32 ebp_670;
				byte SCZO_671;
				word32 ebx_672;
				word32 esi_673;
				word32 edi_674;
				word32 ecx_675;
				word32 eax_676;
				byte SZO_677;
				byte C_678;
				word32 edx_679;
				byte Z_680;
				struct Eq_1585 * es_681;
				struct Eq_1586 * ds_682;
				_acrt_iob_func();
				fn0041113B();
				*(esp_669 - 0x04) = eax_676;
				ptr32 esp_689;
				word32 ebp_690;
				byte SCZO_691;
				word32 ebx_692;
				word32 esi_693;
				word32 edi_694;
				word32 ecx_695;
				ui32 eax_696;
				byte SZO_697;
				byte C_698;
				byte Z_700;
				ucrtbased.dll!fflush();
				fn0041113B();
				esp_159 = esp_689;
				eax_160 = eax_696 | ~0x00;
				goto l00411E4C;
			}
			*(esp_624 - 0x08) = 20000;
			*(esp_624 - 0x0C) = 4291448;
			Eq_254 eax_715 = WaitNamedPipeW(*(esp_624 - 0x0C), *(esp_624 - 0x08));
			fn0041113B();
			esp_14 = (struct Eq_969 *) ((char *) &esp_624->tFFFFFFF4 + 0x04);
			if (eax_715 != 0x00)
				goto l00411A1A;
			esp_624->tFFFFFFF4.u0 = 0x00417BF4;
			word32 edx_724;
			word32 eax_725 = fn0041137F(dwArg00, out edx_724);
			esp_624->tFFFFFFF4.u0 = 0x01;
			ptr32 esp_731;
			word32 ebp_732;
			byte SCZO_733;
			word32 ebx_734;
			word32 esi_735;
			word32 edi_736;
			word32 ecx_737;
			word32 eax_738;
			byte SZO_739;
			byte C_740;
			word32 edx_741;
			byte Z_742;
			struct Eq_1755 * es_743;
			struct Eq_1756 * ds_744;
			_acrt_iob_func();
			fn0041113B();
			*(esp_731 - 0x04) = eax_738;
			ptr32 esp_751;
			word32 ebp_752;
			byte SCZO_753;
			word32 ebx_754;
			word32 esi_755;
			word32 edi_756;
			word32 ecx_757;
			ui32 eax_758;
			byte SZO_759;
			byte C_760;
			byte Z_762;
			ucrtbased.dll!fflush();
			fn0041113B();
			esp_159 = esp_751;
			eax_160 = eax_758 | ~0x00;
l00411E4C:
			struct Eq_1475 * esp_58 = esp_159 - 0x04;
			esp_58->t0000 = edx_153;
			*(esp_58 - 0x04) = eax_160;
			fn004112A3(fp - 0x04, &globals->t411E7C, es_155, ds_156, ebp);
			Eq_254 eax_64 = *(esp_58 - 0x04);
			fn004112B2(eax_64, eax_27 ^ fp - 0x04, esp_58->t0000, esp_58->ptr000C, esp_58->t0008, esp_58->t0004, es_155, ds_156);
			fn0041113B();
			return eax_64;
		}
	}
	LPDWORD * esp_87 = esp_14 - 0x04;
	*esp_87 = (LPDWORD *) null;
	*(esp_87 - 0x04) = 0x00;
	*(esp_87 - 0x08) = fp - 0x0460;
	*(esp_87 - 0x0C) = (HANDLE *) dwLoc10;
	Eq_254 eax_97 = SetNamedPipeHandleState(*(esp_87 - 0x0C), *(esp_87 - 0x08), *(esp_87 - 0x04), *esp_87);
	fn0041113B();
	if (eax_97 == 0x00)
	{
		Eq_254 eax_105 = GetLastError();
		fn0041113B();
		*(esp_87 - 0x08) = (union Eq_254 *) eax_105;
		*(esp_87 - 0x0C) = 0x00417C30;
		word32 edx_112;
		word32 eax_113 = fn004112BC(out edx_112);
		*(esp_87 - 0x0C) = 0x01;
		ptr32 esp_123;
		word32 ebp_124;
		byte SCZO_125;
		word32 ebx_126;
		word32 esi_127;
		word32 edi_128;
		word32 ecx_129;
		word32 eax_130;
		byte SZO_131;
		byte C_132;
		word32 edx_133;
		byte Z_134;
		struct Eq_1448 * es_135;
		struct Eq_1449 * ds_136;
		_acrt_iob_func();
		fn0041113B();
		*(esp_123 - 0x04) = eax_130;
		ptr32 esp_143;
		word32 ebp_144;
		byte SCZO_145;
		word32 ebx_146;
		word32 esi_147;
		word32 edi_148;
		word32 ecx_149;
		ui32 eax_150;
		byte SZO_151;
		byte C_152;
		byte Z_154;
		ucrtbased.dll!fflush();
		fn0041113B();
		esp_159 = esp_143;
		eax_160 = eax_150 | ~0x00;
	}
	else
	{
		*(esp_87 - 0x04) = (LPCVOID *) dwLoc1C_29;
		int32 eax_167 = lstrlenW(*(esp_87 - 0x04));
		fn0041113B();
		*(esp_87 - 0x08) = (LPCVOID *) dwLoc1C_29;
		Eq_254 ecx_171 = eax_167 + 0x02 + eax_167;
		*(esp_87 - 0x0C) = (union Eq_254 *) ecx_171;
		*(esp_87 - 0x10) = 0x00417C90;
		word32 edx_181;
		word32 eax_182 = fn004112BC(out edx_181);
		*(esp_87 - 0x0C) = 0x01;
		ptr32 esp_189;
		word32 ebp_190;
		byte SCZO_191;
		word32 ebx_192;
		word32 esi_193;
		word32 edi_194;
		word32 ecx_195;
		word32 eax_196;
		byte SZO_197;
		byte C_198;
		word32 edx_199;
		byte Z_200;
		struct Eq_1224 * es_201;
		struct Eq_1225 * ds_202;
		_acrt_iob_func();
		fn0041113B();
		*(esp_189 - 0x04) = eax_196;
		struct Eq_1235 * esp_209;
		word32 ebp_210;
		byte SCZO_211;
		word32 ebx_212;
		word32 esi_213;
		word32 edi_214;
		word32 ecx_215;
		word32 eax_216;
		byte SZO_217;
		byte C_218;
		word32 edx_219;
		byte Z_220;
		struct Eq_1247 * es_221;
		struct Eq_1248 * ds_222;
		ucrtbased.dll!fflush();
		fn0041113B();
		*(esp_209 - 0x04) = 0x00;
		*(esp_209 - 0x08) = fp - 0x0454;
		*(esp_209 - 0x0C) = (union Eq_254 *) ecx_171;
		*(esp_209 - 0x10) = (LPCVOID *) dwLoc1C_29;
		*(esp_209 - 0x14) = (HANDLE *) dwLoc10;
		WriteFile(*(esp_209 - 0x14), *(esp_209 - 0x10), *(esp_209 - 0x0C), *(esp_209 - 0x08), *(esp_209 - 0x04));
		fn0041113B();
		*(esp_209 - 0x08) = 0x00;
		*(esp_209 - 0x0C) = fp - 0x0454;
		*(esp_209 - 0x10) = (union Eq_254 *) ecx_171;
		*(esp_209 - 0x14) = (LPCVOID *) dwLoc1C_29;
		*(esp_209 - 0x18) = (HANDLE *) dwLoc10;
		WriteFile(*(esp_209 - 0x18), *(esp_209 - 0x14), *(esp_209 - 0x10), *(esp_209 - 0x0C), *(esp_209 - 0x08));
		fn0041113B();
		esp_209->tFFFFFFF4 = null;
		esp_209->tFFFFFFF0 = fp - 0x0454;
		esp_209->tFFFFFFEC = ecx_171;
		esp_209->tFFFFFFE8 = dwLoc1C_29;
		esp_209->tFFFFFFE4 = dwLoc10;
		Eq_254 eax_281 = WriteFile(esp_209->tFFFFFFE4, esp_209->tFFFFFFE8, esp_209->tFFFFFFEC, esp_209->tFFFFFFF0, esp_209->tFFFFFFF4);
		fn0041113B();
		if (eax_281 == 0x00)
		{
			Eq_254 eax_289 = GetLastError();
			fn0041113B();
			esp_209->tFFFFFFEC = eax_289;
			esp_209->tFFFFFFE8 = (Eq_984) &globals->v417CE0;
			word32 edx_296;
			word32 eax_297 = fn004112BC(out edx_296);
			esp_209->tFFFFFFE8 = (void *) 0x01;
			ptr32 esp_304;
			word32 ebp_305;
			byte SCZO_306;
			word32 ebx_307;
			word32 esi_308;
			word32 edi_309;
			word32 ecx_310;
			word32 eax_311;
			byte SZO_312;
			byte C_313;
			word32 edx_314;
			byte Z_315;
			struct Eq_1703 * es_316;
			struct Eq_1704 * ds_317;
			_acrt_iob_func();
			fn0041113B();
			*(esp_304 - 0x04) = eax_311;
			ptr32 esp_324;
			word32 ebp_325;
			byte SCZO_326;
			word32 ebx_327;
			word32 esi_328;
			word32 edi_329;
			word32 ecx_330;
			ui32 eax_331;
			byte SZO_332;
			byte C_333;
			byte Z_335;
			ucrtbased.dll!fflush();
			fn0041113B();
			esp_159 = esp_324;
			eax_160 = eax_331 | ~0x00;
		}
		else
		{
			esp_209->tFFFFFFF0 = (Eq_1012) &globals->t417D34;
			word32 edx_347;
			word32 eax_348 = fn0041137F(dwArg00, out edx_347);
			esp_209->tFFFFFFF0 = (DWORD *) 0x01;
			ptr32 esp_354;
			word32 ebp_355;
			byte SCZO_356;
			word32 ebx_357;
			word32 esi_358;
			word32 edi_359;
			word32 ecx_360;
			word32 eax_361;
			byte SZO_362;
			byte C_363;
			word32 edx_364;
			byte Z_365;
			struct Eq_1641 * es_366;
			struct Eq_1642 * ds_367;
			_acrt_iob_func();
			fn0041113B();
			*(esp_354 - 0x04) = eax_361;
			LPOVERLAPPED * esp_374;
			word32 ebp_375;
			byte SCZO_376;
			word32 ebx_377;
			word32 esi_378;
			word32 edi_379;
			word32 ecx_380;
			word32 eax_381;
			byte SZO_382;
			byte C_383;
			word32 edx_384;
			byte Z_385;
			struct Eq_1664 * es_386;
			struct Eq_1665 * ds_387;
			ucrtbased.dll!fflush();
			fn0041113B();
			LPOVERLAPPED * esp_390 = esp_374;
			do
			{
				LPOVERLAPPED * esp_400 = esp_390 - 0x04;
				*esp_400 = (LPOVERLAPPED *) null;
				*(esp_400 - 0x04) = fp - 0x043C;
				*(esp_400 - 0x08) = 0x0400;
				*(esp_400 - 0x0C) = fp - 0x0424;
				*(esp_400 - 0x10) = (HANDLE *) dwLoc10;
				Eq_254 eax_413 = ReadFile(*(esp_400 - 0x10), *(esp_400 - 0x0C), *(esp_400 - 0x08), *(esp_400 - 0x04), *esp_400);
				fn0041113B();
				esp_390 = esp_400;
				if (eax_413 == 0x00)
				{
					Eq_254 eax_618 = GetLastError();
					fn0041113B();
					esp_390 = (LPOVERLAPPED *) ((char *) esp_400 - 0x04);
					if (eax_618 != 0xEA)
						break;
				}
				ptr32 * esp_566 = esp_390 - 0x04;
				*esp_566 = fp - 0x0424;
				*(esp_566 - 0x04) = 0x00417D74;
				word32 edx_570;
				word32 eax_571 = fn004112BC(out edx_570);
				*(esp_566 - 0x04) = 0x01;
				ptr32 esp_578;
				word32 ebp_579;
				byte SCZO_580;
				word32 ebx_581;
				word32 esi_582;
				word32 edi_583;
				word32 ecx_584;
				word32 eax_585;
				byte SZO_586;
				byte C_587;
				word32 edx_588;
				byte Z_589;
				struct Eq_1819 * es_590;
				struct Eq_1820 * ds_591;
				_acrt_iob_func();
				fn0041113B();
				*(esp_578 - 0x04) = eax_585;
				LPOVERLAPPED * esp_598;
				word32 ebp_599;
				byte SCZO_600;
				word32 ebx_601;
				word32 esi_602;
				word32 edi_603;
				word32 ecx_604;
				word32 eax_605;
				byte SZO_606;
				byte C_607;
				word32 edx_608;
				byte Z_609;
				struct Eq_1842 * es_610;
				struct Eq_1843 * ds_611;
				ucrtbased.dll!fflush();
				fn0041113B();
				esp_390 = esp_598;
			} while (eax_413 == 0x00);
			if (eax_413 == 0x00)
			{
				Eq_254 eax_435 = GetLastError();
				fn0041113B();
				ptr32 esp_437 = (char *) esp_390 - 0x04;
				*(esp_437 - 0x04) = (union Eq_254 *) eax_435;
				*(esp_437 - 0x08) = 0x00417D88;
				word32 edx_442;
				word32 eax_443 = fn004112BC(out edx_442);
				*(esp_437 - 0x08) = 0x01;
				ptr32 esp_450;
				word32 ebp_451;
				byte SCZO_452;
				word32 ebx_453;
				word32 esi_454;
				word32 edi_455;
				word32 ecx_456;
				word32 eax_457;
				byte SZO_458;
				byte C_459;
				word32 edx_460;
				byte Z_461;
				struct Eq_1993 * es_462;
				struct Eq_1994 * ds_463;
				_acrt_iob_func();
				fn0041113B();
				*(esp_450 - 0x04) = eax_457;
				ptr32 esp_470;
				word32 ebp_471;
				byte SCZO_472;
				word32 ebx_473;
				word32 esi_474;
				word32 edi_475;
				word32 ecx_476;
				ui32 eax_477;
				byte SZO_478;
				byte C_479;
				byte Z_481;
				ucrtbased.dll!fflush();
				fn0041113B();
				esp_159 = esp_470;
				eax_160 = eax_477 | ~0x00;
			}
			else
			{
				word32 * esp_490 = esp_390 - 0x04;
				*esp_490 = 4292064;
				word32 edx_492;
				word32 eax_493 = fn0041137F(dwArg00, out edx_492);
				*esp_490 = 0x01;
				ptr32 esp_499;
				word32 ebp_500;
				byte SCZO_501;
				word32 ebx_502;
				word32 esi_503;
				word32 edi_504;
				word32 ecx_505;
				word32 eax_506;
				byte SZO_507;
				byte C_508;
				word32 edx_509;
				byte Z_510;
				struct Eq_1890 * es_511;
				struct Eq_1891 * ds_512;
				_acrt_iob_func();
				fn0041113B();
				*(esp_499 - 0x04) = eax_506;
				word32 esp_519;
				word32 ebp_520;
				byte SCZO_521;
				word32 ebx_522;
				word32 esi_523;
				word32 edi_524;
				word32 ecx_525;
				word32 eax_526;
				byte SZO_527;
				byte C_528;
				word32 edx_529;
				byte Z_530;
				struct Eq_1913 * es_531;
				struct Eq_1914 * ds_532;
				ucrtbased.dll!fflush();
				fn0041113B();
				ptr32 esp_537;
				word32 ebp_538;
				byte SCZO_539;
				word32 ebx_540;
				word32 esi_541;
				word32 edi_542;
				word32 ecx_543;
				word32 eax_544;
				byte SZO_545;
				byte C_546;
				byte Z_548;
				getch();
				fn0041113B();
				*(esp_537 - 0x08) = (HANDLE *) dwLoc10;
				CloseHandle(*(esp_537 - 0x08));
				fn0041113B();
				esp_159 = esp_537 + ~0x07;
				eax_160 = 0x00;
			}
		}
	}
	goto l00411E4C;
}

// 00411190: void fn00411190(Stack byte bArg04, Stack byte bArg08)
void fn00411190(byte bArg04, byte bArg08)
{
	if ((word32) globals->b41A53C == 0x00 || (word32) bArg08 == 0x00)
	{
		fn0041101E();
		fn00411235();
	}
	return;
}

// 004111C7: Register word32 fn004111C7(Stack ptr32 dwArg04, Stack word32 dwArg08, Stack word32 dwArg0C, Stack word32 dwArg10, Register out ptr32 edxOut)
word32 fn004111C7(ptr32 dwArg04, word32 dwArg08, word32 dwArg0C, word32 dwArg10, ptr32 & edxOut)
{
	word32 * edi_17 = fp - 0xC4;
	word32 ecx_18 = 0x30;
	while (ecx_18 != 0x00)
	{
		*edi_17 = 0xCCCCCCCC;
		edi_17 = edi_17 + 0x01;
		ecx_18 = ecx_18 - 0x01;
	}
	word32 eax_42 = fn00411398();
	word32 esp_50;
	word32 ebp_51;
	byte SCZO_52;
	word32 ebx_53;
	word32 esi_54;
	word32 edi_55;
	word32 ecx_56;
	word32 eax_57;
	word32 edx_58;
	_stdio_common_vfprintf();
	fn0041113B();
	fn0041113B();
	return eax_57;
}

// 004111E0: void fn004111E0()
void fn004111E0()
{
	word32 esp_2;
	register_thread_local_exe_atexit_callback();
	return;
}

// 004111F9: Register word32 fn004111F9()
word32 fn004111F9()
{
	return fn00413030(dwArg00);
}

// 00411203: void fn00411203()
void fn00411203()
{
	word32 * edi_17 = fp - 0xC4;
	word32 ecx_18 = 0x30;
	while (ecx_18 != 0x00)
	{
		*edi_17 = 0xCCCCCCCC;
		edi_17 = edi_17 + 0x01;
		ecx_18 = ecx_18 - 0x01;
	}
	return;
}

// 00411230: Register word32 fn00411230(Register out ptr32 ecxOut, Register out ptr32 edxOut)
word32 fn00411230(ptr32 & ecxOut, ptr32 & edxOut)
{
	word32 ecx_2;
	word32 edx_3;
	return fn00413E60(out ecx_2, out edx_3);
}

// 00411235: void fn00411235()
void fn00411235()
{
	return;
}

// 0041123F: Register word32 fn0041123F(Stack ptr32 dwArg04, Stack word32 dwArg08, Stack word32 dwArg0C, Stack word32 dwArg10, Register out ptr32 edxOut)
word32 fn0041123F(ptr32 dwArg04, word32 dwArg08, word32 dwArg0C, word32 dwArg10, ptr32 & edxOut)
{
	word32 * edi_17 = fp - 0xC4;
	word32 ecx_18 = 0x30;
	while (ecx_18 != 0x00)
	{
		*edi_17 = 0xCCCCCCCC;
		edi_17 = edi_17 + 0x01;
		ecx_18 = ecx_18 - 0x01;
	}
	word32 eax_42 = fn00411398();
	word32 esp_50;
	word32 ebp_51;
	byte SCZO_52;
	word32 ebx_53;
	word32 esi_54;
	word32 edi_55;
	word32 ecx_56;
	word32 eax_57;
	word32 edx_58;
	_stdio_common_vfwprintf();
	fn0041113B();
	fn0041113B();
	return eax_57;
}

// 00411258: void fn00411258()
void fn00411258()
{
	return;
}

// 004112A3: void fn004112A3(Register Eq_51 ecx, Register (ptr Eq_407) edx, Register (ptr Eq_56) es, Register (ptr Eq_57) ds, Stack ptr32 dwArg00)
void fn004112A3(Eq_51 ecx, Eq_407 * edx, Eq_56 * es, Eq_57 * ds, ptr32 dwArg00)
{
	Eq_51 esi_18 = 0x00;
	if (edx->t0000 <= 0x00)
		return;
	word32 * esp_45 = fp - 0x14;
	Eq_55 edi_47 = 0x00;
l004121D4:
	struct Eq_2235 * ecx_54 = edx->ptr0004;
	word32 edx_56 = Mem0[ecx_54 + edi_47:word32];
	if (Mem0[edx_56 - 0x04 + ecx:word32] == 0xCCCCCCCC)
	{
		edx_56 = ecx;
		if (Mem0[Mem0[ecx_54 + 0x04 + edi_47:word32] + edx_56 + ecx:word32] == 0xCCCCCCCC)
		{
l00412209:
			esi_18 = (word32) esi_18.u0 + 0x01;
			edi_47 = (word32) edi_47.u0 + 0x0C;
			if (esi_18 < edx->t0000)
				goto l004121D4;
			return;
		}
	}
	word32 * esp_72 = esp_45 - 0x04;
	Mem73[esp_72 + 0x00:word32] = Mem0[ecx_54 + 0x08 + edi_47:word32];
	*(esp_72 - 0x04) = dwArg00;
	fn004110F5(edx_56, edx, esi_18, edi_47, es, ds);
	esp_45 = esp_72;
	goto l00412209;
}

// 004112AD: void fn004112AD()
void fn004112AD()
{
	word32 esp_2;
	_p___argc();
	return;
}

// 004112B2: void fn004112B2(Register Eq_254 eax, Register ui32 ecx, Register Eq_51 edx, Register (ptr Eq_407) ebx, Register Eq_51 esi, Register Eq_55 edi, Register (ptr Eq_56) es, Register (ptr Eq_57) ds)
void fn004112B2(Eq_254 eax, ui32 ecx, Eq_51 edx, Eq_407 * ebx, Eq_51 esi, Eq_55 edi, Eq_56 * es, Eq_57 * ds)
{
	if (ecx != globals->dw41A000)
	{
		fn00413070(eax, ecx, edx, ebx, esi, edi, es, ds);
		return;
	}
	else
		return;
}

// 004112B7: void fn004112B7()
void fn004112B7()
{
	return;
}

// 004112BC: Register word32 fn004112BC(Register out ptr32 edxOut)
word32 fn004112BC(ptr32 & edxOut)
{
	word32 edx_3;
	return fn00411FB0(dwArg00, out edx_3);
}

// 004112C6: void fn004112C6(Register Eq_51 edx, Register word32 ebx, Register Eq_55 edi, Register (ptr Eq_56) es, Register (ptr Eq_57) ds)
void fn004112C6(Eq_51 edx, word32 ebx, Eq_55 edi, Eq_56 * es, Eq_57 * ds)
{
	fn00413920(edx, ebx, edi, es, ds, dwArg00);
	return;
}

// 004112DF: Register Eq_2 fn004112DF(Stack (ptr wchar_t) ptrArg04, Stack (ptr wchar_t) ptrArg08, Stack Eq_4 tArg0C, Stack (ptr wchar_t) ptrArg10, Stack Eq_4 tArg14, Stack (ptr wchar_t) ptrArg18, Stack Eq_4 tArg1C, Stack (ptr wchar_t) ptrArg20, Stack Eq_4 tArg24)
errno_t fn004112DF(wchar_t * ptrArg04, wchar_t * ptrArg08, size_t tArg0C, wchar_t * ptrArg10, size_t tArg14, wchar_t * ptrArg18, size_t tArg1C, wchar_t * ptrArg20, size_t tArg24)
{
	return _wsplitpath_s(ptrArg04, ptrArg08, tArg0C, ptrArg10, tArg14, ptrArg18, tArg1C, ptrArg20, tArg24);
}

// 004112EE: Register Eq_254 Win32CrtStartup()
Eq_254 Win32CrtStartup()
{
	fn00412410(ebx, esi, edi, es, ds);
	return eax;
}

// 0041130C: void fn0041130C()
void fn0041130C()
{
	word32 esp_12;
	word32 ebp_13;
	word32 ecx_14;
	globals->ptr41C000();
	return;
}

// 0041131B: void fn0041131B(Stack int32 dwArg04)
void fn0041131B(int32 dwArg04)
{
	exit(dwArg04);
	return;
}

// 00411320: void fn00411320()
void fn00411320()
{
	word32 esp_2;
	initterm();
	return;
}

// 00411339: void fn00411339()
void fn00411339()
{
	word32 esp_2;
	_vcrt_GetModuleFileNameW();
	return;
}

// 00411348: void fn00411348()
void fn00411348()
{
fn00411348_entry:
l00411348:
fn00411348_exit:
}

// 00411352: Register word32 fn00411352()
word32 fn00411352()
{
	return globals->dw41A50C;
}

// 00411366: void fn00411366(Stack byte bArg04)
void fn00411366(byte bArg04)
{
	if (fn00411073() != 0x00)
	{
		if ((word32) bArg04 == 0x00)
			globals->dw41A538 = 0x00;
	}
	return;
}

// 00411370: Register word32 fn00411370(Register out ptr32 ecxOut, Register out ptr32 edxOut)
word32 fn00411370(ptr32 & ecxOut, ptr32 & edxOut)
{
	*ecxOut = ecx;
	*edxOut = edx;
	word32 eax_19;
	word32 eax_8 = fn00411073();
	if (eax_8 == 0x00)
		eax_19 = DPB(eax_8, 0x00, 0);
	else
	{
		word32 eax_37 = fn00411082()->dw0004;
		do
		{
			__lock();
			word32 eax_42;
			__cmpxchg(globals->dw41A538, eax_37, 0x00, out eax_42);
			word32 ecx_39;
			*ecxOut = eax_37;
			word32 edx_40;
			*edxOut = 4302136;
			if (eax_42 == 0x00)
			{
				eax_19 = DPB(eax_42, 0x00, 0);
				return eax_19;
			}
		} while (eax_37 != eax_42);
		eax_19 = DPB(eax_37, 0x01, 0);
	}
	return eax_19;
}

// 0041137A: Register Eq_51 fn0041137A(Register ptr32 ebx, Register word32 edi, Register (ptr Eq_56) es, Register (ptr Eq_57) ds, Stack ui32 dwArg04, Stack (ptr word16) dwArg08, Stack (ptr ui32) dwArg10, Stack ptr32 dwArg14, Stack word32 dwArg18, Register out ptr32 ediOut)
Eq_51 fn0041137A(ptr32 ebx, word32 edi, Eq_56 * es, Eq_57 * ds, ui32 dwArg04, word16 * dwArg08, ui32 * dwArg10, ptr32 dwArg14, word32 dwArg18, ptr32 & ediOut)
{
	*ediOut = edi;
	*dwArg10 = 0x00;
	*dwArg08 = 0x00;
	Eq_2452 eax_28 = VirtualQuery(dwArg04 - 0x01, fp - 0x50, 0x1C);
	if (eax_28 == 0x00)
		return edx;
	fn00411339();
	if (eax_28 == 0x00 || dwLoc4C->w0000 != 23117)
		return edx;
	struct Eq_2478 * ecx_108 = dwLoc4C->ptr003C;
	if (ecx_108 <= null)
		return edx;
	word32 ecx_112 = ecx_108 + dwLoc4C;
	if (ecx_112->dw0000 != 0x4550)
		return edx;
	int32 edx_116 = (word32) ecx_112->w0014;
	Eq_51 esi_117 = dwArg04 - 0x01 - dwLoc4C;
	Eq_55 edi_122 = (word32) ecx_112->w0006;
	Eq_51 edx_123 = edx_116 + 0x20;
	struct Eq_407 * ebx_124 = null;
	Eq_55 eax_125 = 0x00;
	if (edi_122 != 0x00)
	{
		struct Eq_2514 * ecx_761 = &(ecx_112 + (edx_116 + 0x20) / 22)->dw0000 + 0x01;
		do
		{
			edx_123.u1 = ecx_761->dw0000;
			if (esi_117 >= edx_123)
			{
				ebx_124 = esi_117 - edx_123;
				if (esi_117 < ecx_761->dw0000)
					break;
			}
			eax_125 = (word32) eax_125.u1 + 0x01;
			ecx_761 = ecx_761 + 0x01;
		} while (eax_125 < edi_122);
	}
	if (eax_125 != edi_122)
	{
		Eq_254 eax_170;
		word32 eax_162 = (word32) eax_125 + 0x01;
		if (globals->b41A56D != 0x00)
		{
			eax_170 = globals->t41A568;
			goto l00414B6D;
		}
		if (globals->t41A568 != 0x00)
			goto l00414BA4;
		word32 ebx_751;
		eax_170 = fn004144E0(edx_123, ebx_124, fp - 0x04, esi_117, edi_122, es, ds, out edx_123, out ebx_751);
		globals->t41A568 = eax_170;
		if (eax_170 != 0x00)
		{
			globals->b41A56D = 0x01;
l00414B6D:
			Eq_254 eax_175 = GetProcAddress(eax_170, &globals->t4187C4);
			if (eax_175 != 0x00)
			{
				fn0041130C();
				if (eax_175() != 0x00)
				{
					struct Eq_2588 * eax_226 = *dwLoc1C;
					<anonymous> * esi_227 = eax_226->ptr0000;
					fn0041130C();
					ptr32 esp_230;
					word32 ebp_231;
					word32 eax_232;
					byte SCZO_233;
					word32 ecx_234;
					byte SZO_235;
					byte C_236;
					word32 esi_237;
					word16 cx_238;
					byte Z_239;
					word32 edx_240;
					word32 ebx_241;
					word32 edi_242;
					byte al_243;
					byte CZ_244;
					bcuiposr0 None_245;
					struct Eq_2615 * es_246;
					struct Eq_2616 * ds_247;
					esi_227();
					if (eax_232 == 20091201)
					{
						*(esp_230 - 0x04) = fp - 0x24;
						*(esp_230 - 0x08) = 4294616;
						*(esp_230 - 0x0C) = 0x00;
						struct Eq_2588 * eax_293 = *dwLoc1C;
						<anonymous> * esi_294 = eax_293->ptr001C;
						fn0041130C();
						ptr32 esp_297;
						word32 ebp_298;
						word32 eax_299;
						byte SCZO_300;
						word32 ecx_301;
						byte SZO_302;
						byte C_303;
						word32 esi_304;
						word16 cx_305;
						byte Z_306;
						word32 edx_307;
						word32 ebx_308;
						word32 edi_309;
						byte al_310;
						byte CZ_311;
						bcuiposr0 None_312;
						struct Eq_2697 * es_313;
						struct Eq_2698 * ds_314;
						esi_294();
						if (eax_299 != 0x00)
						{
							*(esp_297 - 0x04) = 0x00;
							*(esp_297 - 0x08) = 0x00;
							*(esp_297 - 0x0C) = 0x00;
							struct Eq_2719 * esi_327 = *dwLoc24;
							*(esp_297 - 0x10) = fp - 0x18;
							*(esp_297 - 0x14) = ebx_308;
							*(esp_297 - 0x18) = eax_162;
							<anonymous> * esi_335 = esi_327->ptr0020;
							fn0041130C();
							ptr32 esp_338;
							word32 ebp_339;
							word32 eax_340;
							byte SCZO_341;
							word32 ecx_342;
							byte SZO_343;
							byte C_344;
							word32 esi_345;
							word16 cx_346;
							byte Z_347;
							word32 edx_348;
							word32 ebx_349;
							word32 edi_350;
							byte al_351;
							byte CZ_352;
							bcuiposr0 None_353;
							struct Eq_2763 * es_354;
							struct Eq_2764 * ds_355;
							esi_335();
							if (eax_340 != 0x00)
							{
								*(esp_338 - 0x04) = fp - 0x0C;
								struct Eq_2802 * eax_391 = *dwLoc18;
								<anonymous> * esi_393 = eax_391->ptr0068;
								fn0041130C();
								word32 esp_396;
								word32 ebp_397;
								word32 eax_398;
								byte SCZO_399;
								word32 ecx_400;
								byte SZO_401;
								byte C_402;
								word32 esi_403;
								word16 cx_404;
								byte Z_405;
								word32 edx_406;
								word32 ebx_407;
								word32 edi_408;
								byte al_409;
								byte CZ_410;
								bcuiposr0 None_411;
								struct Eq_2829 * es_412;
								struct Eq_2830 * ds_413;
								esi_393();
								if (al_409 != 0x00 && 0x00 != 0x00)
								{
									ptr32 esp_517;
									struct Eq_2865 * eax_446 = null;
									<anonymous> * esi_450 = eax_446->ptr0008;
									fn0041130C();
									ptr32 esp_453;
									word32 ebp_454;
									word32 eax_455;
									byte SCZO_456;
									word32 ecx_457;
									byte SZO_458;
									byte C_459;
									word32 esi_460;
									word16 cx_461;
									byte Z_462;
									word32 edx_463;
									word32 ebx_464;
									byte al_466;
									byte CZ_467;
									bcuiposr0 None_468;
									struct Eq_2889 * es_469;
									struct Eq_2890 * ds_470;
									Eq_2054 edi_465;
									esi_450();
									esp_517 = esp_453;
									esp_517 = esp_453;
									if (eax_455 != 0x00)
									{
l00414C68:
										word32 * esp_530 = esp_517 - 0x04;
										*esp_530 = 0x00;
										*(esp_530 - 0x04) = fp - 0x14;
										struct Eq_2865 * esi_535 = null;
										*(esp_530 - 0x08) = fp - 44;
										*(esp_530 - 0x0C) = fp - 0x08;
										<anonymous> * esi_541 = esi_535->ptr000C;
										*(esp_530 - 0x10) = fp - 0x20;
										*(esp_530 - 0x14) = 0x00;
										fn0041130C();
										ptr32 esp_550;
										word32 ebp_551;
										word32 eax_552;
										byte SCZO_553;
										word32 ecx_554;
										byte SZO_555;
										byte C_556;
										word32 esi_557;
										word16 cx_558;
										byte Z_559;
										word32 edx_560;
										uint32 ebx_561;
										word32 edi_562;
										byte al_563;
										byte CZ_564;
										bcuiposr0 None_565;
										struct Eq_2998 * es_566;
										struct Eq_2999 * ds_567;
										esi_541();
										if (al_563 == 0x00)
											goto l00414CD5;
										if ((word32) wLoc08 == eax_162 && (dwLoc20 <= ebx_561 && ebx_561 < dwLoc2C + dwLoc20))
										{
											if (dwLoc14 == 0x00 || dwLoc14 >= 0x1FFFFFFF)
												goto l00414CD5;
											*(esp_550 - 0x04) = dwLoc14 << 0x03;
											*(esp_550 - 0x08) = 0x00;
											*(esp_550 - 0x0C) = (HANDLE *) GetProcessHeap();
											Eq_2054 eax_630 = HeapAlloc(*(esp_550 - 0x0C), *(esp_550 - 0x08), *(esp_550 - 0x04));
											if (eax_630 == 0x00)
												goto l00414CD5;
											*(esp_550 - 0x04) = (union Eq_2054 *) eax_630;
											*(esp_550 - 0x08) = fp - 0x14;
											struct Eq_2865 * esi_643 = null;
											*(esp_550 - 0x0C) = 0x00;
											*(esp_550 - 0x10) = 0x00;
											*(esp_550 - 0x14) = 0x00;
											<anonymous> * esi_652 = esi_643->ptr000C;
											*(esp_550 - 0x18) = fp - 0x30;
											fn0041130C();
											word32 ebp_658;
											word32 eax_659;
											byte SCZO_660;
											word32 ecx_661;
											byte SZO_662;
											byte C_663;
											word32 esi_664;
											word16 cx_665;
											byte Z_666;
											word32 edx_667;
											word32 ebx_668;
											word32 edi_669;
											byte al_670;
											byte CZ_671;
											bcuiposr0 None_672;
											struct Eq_3175 * es_673;
											struct Eq_3176 * ds_674;
											esi_652();
											edi_465 = eax_630;
											if (al_670 != 0x00)
											{
												uint32 ebx_679 = ebx_668 - dwLoc20;
												if (ebx_679 >= *eax_630)
												{
													uint32 eax_684 = 0x01;
													if (dwLoc14 > 0x01)
													{
														do
														{
															if (ebx_679 < *((word32) eax_630 + eax_684 * 0x08))
																goto l00414DA0;
															eax_684 = eax_684 + 0x01;
														} while (eax_684 < dwLoc14);
													}
l00414DA0:
													uint32 eax_689 = *((word32) (eax_630 - 0x04) + eax_684 * 0x08);
													*(esp_517 - 0x04) = 0x00;
													*(esp_517 - 0x08) = 0x00;
													*dwArg10 = eax_689 & 0x00FFFFFF;
													struct Eq_2802 * esi_702 = *dwLoc18;
													*(esp_517 - 0x0C) = 0x00;
													*(esp_517 - 0x10) = fp + 0x0C;
													*(esp_517 - 0x14) = (word16 **) dwArg08;
													<anonymous> * esi_710 = esi_702->ptr0070;
													*(esp_517 - 0x18) = dwLoc30;
													fn0041130C();
													word32 ebp_718;
													word32 eax_719;
													byte SCZO_720;
													word32 ecx_721;
													byte SZO_722;
													byte C_723;
													word32 esi_724;
													word16 cx_725;
													byte Z_726;
													word32 edx_727;
													word32 ebx_728;
													word32 edi_729;
													byte al_730;
													byte CZ_731;
													bcuiposr0 None_732;
													struct Eq_3261 * es_733;
													struct Eq_3262 * ds_734;
													esi_710();
													edi_465 = eax_630;
												}
											}
											goto l00414CC5;
										}
										struct Eq_2865 * eax_576 = null;
										<anonymous> * esi_577 = eax_576->ptr0008;
										fn0041130C();
										word32 ebp_581;
										word32 eax_582;
										byte SCZO_583;
										word32 ecx_584;
										byte SZO_585;
										byte C_586;
										word32 esi_587;
										word16 cx_588;
										byte Z_589;
										word32 edx_590;
										word32 ebx_591;
										word32 edi_592;
										byte al_593;
										byte CZ_594;
										bcuiposr0 None_595;
										struct Eq_3056 * es_596;
										struct Eq_3057 * ds_597;
										esi_577();
										if (eax_582 != 0x00)
											goto l00414C68;
										&edi_465.u0->dw0000 = 0x00;
									}
l00414CC5:
									union Eq_2054 * esp_518 = esp_517 - 0x04;
									*esp_518 = (union Eq_2054 *) edi_465;
									*(esp_518 - 0x04) = 0x00;
									*(esp_518 - 0x08) = (HANDLE *) GetProcessHeap();
									HeapFree(*(esp_518 - 0x08), *(esp_518 - 0x04), *esp_518);
l00414CD5:
									struct Eq_2865 * eax_477 = null;
									<anonymous> * esi_478 = eax_477->ptr0000;
									fn0041130C();
									word32 esp_481;
									word32 ebp_482;
									word32 eax_483;
									byte SCZO_484;
									word32 ecx_485;
									byte SZO_486;
									byte C_487;
									word32 esi_488;
									word16 cx_489;
									byte Z_490;
									word32 edx_491;
									word32 ebx_492;
									word32 edi_493;
									byte al_494;
									byte CZ_495;
									bcuiposr0 None_496;
									struct Eq_3027 * es_497;
									struct Eq_3028 * ds_498;
									esi_478();
								}
								struct Eq_2802 * eax_420 = *dwLoc18;
								<anonymous> * esi_421 = eax_420->ptr0040;
								fn0041130C();
								word32 esp_424;
								word32 ebp_425;
								word32 eax_426;
								byte SCZO_427;
								word32 ecx_428;
								byte SZO_429;
								byte C_430;
								word32 esi_431;
								word16 cx_432;
								byte Z_433;
								word32 edx_434;
								word32 ebx_435;
								word32 edi_436;
								byte al_437;
								byte CZ_438;
								bcuiposr0 None_439;
								struct Eq_2859 * es_440;
								struct Eq_2860 * ds_441;
								esi_421();
							}
							struct Eq_2719 * eax_363 = *dwLoc24;
							<anonymous> * esi_364 = eax_363->ptr0038;
							fn0041130C();
							word32 esp_367;
							word32 ebp_368;
							word32 eax_369;
							byte SCZO_370;
							word32 ecx_371;
							byte SZO_372;
							byte C_373;
							word32 esi_374;
							word16 cx_375;
							byte Z_376;
							word32 edx_377;
							word32 ebx_378;
							word32 edi_379;
							byte al_380;
							byte CZ_381;
							bcuiposr0 None_382;
							struct Eq_2793 * es_383;
							struct Eq_2794 * ds_384;
							esi_364();
						}
					}
					struct Eq_2588 * edx_254 = *dwLoc1C;
					<anonymous> * esi_255 = edx_254->ptr002C;
					fn0041130C();
					word32 * esp_258;
					word32 ebp_259;
					word32 eax_260;
					byte SCZO_261;
					word32 ecx_262;
					byte SZO_263;
					byte C_264;
					word32 esi_265;
					word16 cx_266;
					byte Z_267;
					Eq_51 edx_268;
					word32 ebx_269;
					word32 edi_270;
					byte al_271;
					byte CZ_272;
					bcuiposr0 None_273;
					struct Eq_2645 * es_274;
					struct Eq_2646 * ds_275;
					esi_255();
					word32 edi_277;
					*ediOut = *esp_258;
					return edx_268;
				}
			}
			goto l00414BA4;
		}
	}
l00414BA4:
	word32 edi_151;
	*ediOut = edi;
	return edx_123;
}

// 0041137F: Register word32 fn0041137F(Stack word32 dwArg04, Register out ptr32 edxOut)
word32 fn0041137F(word32 dwArg04, ptr32 & edxOut)
{
	word32 * edi_17 = fp - 220;
	word32 ecx_18 = 0x36;
	while (ecx_18 != 0x00)
	{
		*edi_17 = 0xCCCCCCCC;
		edi_17 = edi_17 + 0x01;
		ecx_18 = ecx_18 - 0x01;
	}
	fn00411203();
	word32 esp_39;
	word32 ebp_40;
	byte SCZO_41;
	word32 ebx_42;
	word32 esi_43;
	word32 edi_44;
	word32 ecx_45;
	word32 eax_46;
	word32 edx_47;
	_acrt_iob_func();
	fn0041113B();
	word32 edx_53;
	word32 eax_54 = fn004111C7(fp + 0x08, 0x01, dwArg04, 0x00, out edx_53);
	fn0041113B();
	return eax_54;
}

// 00411398: Register ptr32 fn00411398()
ptr32 fn00411398()
{
	word32 * edi_17 = fp - 0xC4;
	word32 ecx_18 = 0x30;
	while (ecx_18 != 0x00)
	{
		*edi_17 = 0xCCCCCCCC;
		edi_17 = edi_17 + 0x01;
		ecx_18 = ecx_18 - 0x01;
	}
	return 4301112;
}

// 004113AC: void fn004113AC()
void fn004113AC()
{
	word32 esp_2;
	_vcrt_LoadLibraryExW();
	return;
}

// 004113B1: Register byte fn004113B1(Stack int32 dwArg04)
byte fn004113B1(int32 dwArg04)
{
	byte al_109;
	ptr32 eax_14 = fs->ptr0000;
	fs->ptr0000 = fp - 0x14;
	if ((word32) fn00413690(&globals->t400000) == 0x00)
		al_109 = 0x00;
	else
	{
		struct Eq_3358 * eax_102 = fn004135D0(&globals->t400000, dwArg04 - 0x00400000);
		if (eax_102 == null)
			al_109 = 0x00;
		else if ((eax_102->dw0024 & 0x80000000) != 0x00)
			al_109 = 0x00;
		else
			al_109 = 0x01;
	}
	fs->ptr0000 = eax_14;
	return al_109;
}

// 004113C0: void fn004113C0()
void fn004113C0()
{
	word32 esp_2;
	_p___wargv();
	return;
}

// 004113C5: void fn004113C5()
void fn004113C5()
{
	word32 esp_2;
	_vcrt_GetModuleHandleW();
	return;
}

// 00411FB0: Register word32 fn00411FB0(Stack word32 dwArg04, Register out ptr32 edxOut)
word32 fn00411FB0(word32 dwArg04, ptr32 & edxOut)
{
	word32 * edi_17 = fp - 220;
	word32 ecx_18 = 0x36;
	while (ecx_18 != 0x00)
	{
		*edi_17 = 0xCCCCCCCC;
		edi_17 = edi_17 + 0x01;
		ecx_18 = ecx_18 - 0x01;
	}
	fn0041107D();
	word32 esp_39;
	word32 ebp_40;
	byte SCZO_41;
	word32 ebx_42;
	word32 esi_43;
	word32 edi_44;
	word32 ecx_45;
	word32 eax_46;
	word32 edx_47;
	_acrt_iob_func();
	fn0041113B();
	word32 edx_53;
	word32 eax_54 = fn0041123F(fp + 0x08, 0x01, dwArg04, 0x00, out edx_53);
	fn0041113B();
	return eax_54;
}

// 00412230: void fn00412230()
void fn00412230()
{
	if (Z)
		;
	else
		return;
}

// 00412410: void fn00412410(Register word32 ebx, Register word32 esi, Register Eq_55 edi, Register (ptr Eq_56) es, Register (ptr Eq_57) ds)
void fn00412410(word32 ebx, word32 esi, Eq_55 edi, Eq_56 * es, Eq_57 * ds)
{
	word32 ecx_6;
	Eq_51 edx_7;
	fn00411230(out ecx_6, out edx_7);
	fn00412430(ecx_6, edx_7, ebx, fp - 0x04, esi, edi, es, ds);
	return;
}

// 00412430: void fn00412430(Register word32 ecx, Register Eq_51 edx, Register word32 ebx, Register ptr32 ebp, Register word32 esi, Register Eq_55 edi, Register (ptr Eq_56) es, Register (ptr Eq_57) ds)
void fn00412430(word32 ecx, Eq_51 edx, word32 ebx, ptr32 ebp, word32 esi, Eq_55 edi, Eq_56 * es, Eq_57 * ds)
{
	fs->ptr0000 = fp - 0x14;
	fn004112C6(edx, ebx, edi, es, ds);
	ptr32 ebp_108 = fp - 0x04;
	word32 * esp_201 = &fp->dwFFFFFFA4 + 0x01;
	word32 eax_47 = (word32) (byte) (fp - 0x14);
	if (eax_47 == 0x00)
	{
		fp->dwFFFFFFA4 = 0x07;
		fn0041106E(eax_47, ecx, edx, ebx, fp - 0x04, esi, edi, es, ds);
		esp_201 = (word32 *) &fp->dwFFFFFFA4;
	}
	*(fp - 0x1D) = 0x00;
	*(fp - 0x08) = 0x00;
	word32 ecx_55;
	Eq_51 edx_56;
	word32 eax_57 = fn00411370(out ecx_55, out edx_56);
	*(fp - 0x1E) = (byte) eax_57;
	if (globals->dw41A534 == 0x01)
	{
		esp_201 = esp_201 - 0x04;
		*esp_201 = 0x07;
		fn0041106E(eax_57, ecx_55, edx_56, ebx, fp - 0x04, esi, edi, es, ds);
	}
	else if (globals->dw41A534 == 0x00)
	{
		globals->dw41A534 = 0x01;
		word32 * esp_206 = esp_201 - 0x04;
		*esp_206 = 4290072;
		*(esp_206 - 0x04) = 4289292;
		fn004110A0();
		if (eax_57 != 0x00)
		{
			*(fp - 0x3C) = 0xFF;
			*(fp - 0x08) = ~0x01;
			goto l0041262B;
		}
		*esp_206 = 0x00417208;
		*(esp_206 - 0x04) = 0x00417000;
		fn00411320();
		globals->dw41A534 = 0x02;
		esp_201 = esp_206 + 0x01;
	}
	else
		*(fp - 0x1D) = 0x01;
	word32 * esp_90 = esp_201 - 0x04;
	*esp_90 = (word32) *(fp - 0x1E);
	fn00411366(bArg00);
	fn004112B7();
	*(fp - 0x24) = 0x0041A588;
	word32 * esp_109 = esp_90 + 0x01;
	if (**(fp - 0x24) != 0x00)
	{
		*esp_90 = *(fp - 0x24);
		byte al_169 = fn004113B1(dwArg00);
		esp_109 = esp_90 + 0x01;
		if ((word32) al_169 != 0x00)
		{
			*esp_90 = 0x00;
			*(esp_90 - 0x04) = 0x02;
			*(esp_90 - 0x08) = 0x00;
			word32 * edx_181 = *(fp - 0x24);
			word32 eax_182 = *edx_181;
			*(fp - 44) = eax_182;
			fn0041130C();
			word32 eax_187;
			byte SCZO_189;
			word32 ebx_190;
			word32 esi_191;
			word32 edi_192;
			byte SZO_193;
			byte C_194;
			byte al_195;
			byte Z_196;
			word32 ecx_197;
			word32 edx_198;
			(*(fp - 44))();
		}
	}
	word32 ** eax_110 = fn004110E1();
	*(ebp_108 - 0x24) = 4302204;
	if (**(ebp_108 - 0x24) != 0x00)
	{
		word32 * esp_151 = esp_109 - 0x04;
		*esp_151 = *(ebp_108 - 0x24);
		eax_110 = (word32) fn004113B1(dwArg00);
		if (eax_110 != null)
		{
			*esp_151 = **(ebp_108 - 0x24);
			fn004111E0();
		}
	}
	*(ebp_108 - 44) = fn004126F0(eax_110, ebp_108, es, ds);
	word32 * esp_120 = esp_109;
	if ((word32) fn00411145() == 0x00)
	{
		esp_120 = esp_109 - 0x04;
		*esp_120 = *(ebp_108 - 44);
		fn0041131B(dwArg00);
	}
	if ((word32) *(ebp_108 - 0x19) == 0x00)
		fn004110B9();
	word32 * esp_134 = esp_120 - 0x04;
	*esp_134 = 0x00;
	*(esp_134 - 0x04) = 0x01;
	fn00411190(bArg00, bArg04);
	*(ebp_108 - 0x3C) = *(ebp_108 - 44);
	*(ebp_108 - 0x04) = ~0x01;
l0041262B:
	fs->ptr0000 = *(ebp_108 - 0x10);
	return;
}

// 004126F0: Register (ptr (ptr word32)) fn004126F0(Register (ptr (ptr word32)) eax, Register ptr32 ebp, Register (ptr Eq_56) es, Register (ptr Eq_57) ds)
word32 * * fn004126F0(word32 * * eax, ptr32 ebp, Eq_56 * es, Eq_57 * ds)
{
	fn004110D2();
	*(fp - 0x08) = eax;
	fn004113C0();
	word32 * eax_9 = *eax;
	*(fp - 0x0C) = eax_9;
	fn004112AD();
	*(fp - 0x10) = *eax_9;
	return fn00411154(fp - 0x04, es, ds, dwArg00, dwArg04);
}

// 00412790: Register word32 fn00412790(Stack word32 dwArg04)
word32 fn00412790(word32 dwArg04)
{
	ptr32 eax_14 = fs->ptr0000;
	fs->ptr0000 = fp - 0x14;
	RaiseException(1080890248, 0x00, 0x06, fp - 0x38);
	fs->ptr0000 = eax_14;
	return 0x00;
}

// 00412850: Register word32 fn00412850(Stack ui32 dwArg04, Stack word32 dwArg08, Stack word32 dwArg0C, Stack ptr32 dwArg10)
word32 fn00412850(ui32 dwArg04, word32 dwArg08, word32 dwArg0C, ptr32 dwArg10)
{
	ptr32 eax_14 = fs->ptr0000;
	fs->ptr0000 = fp - 0x14;
	RaiseException(1080890248, 0x00, 0x06, fp - 0x38);
	fs->ptr0000 = eax_14;
	return 0x00;
}

// 00412AC0: void fn00412AC0(Register Eq_51 edx, Register (ptr Eq_407) ebx, Register Eq_51 esi, Register Eq_55 edi, Register (ptr Eq_56) es, Register (ptr Eq_57) ds, Stack word32 dwArg04, Stack (ptr char) dwArg08)
void fn00412AC0(Eq_51 edx, Eq_407 * ebx, Eq_51 esi, Eq_55 edi, Eq_56 * es, Eq_57 * ds, word32 dwArg04, char * dwArg08)
{
	Eq_254 eax_50;
	Eq_254 eax_9 = globals->dw41A000 ^ fp - 0x04;
	word32 edi_24 = globals->dw41A014;
	eax_50 = eax_9;
	if (edi_24 != ~0x00)
	{
		Eq_2577 eax_126;
		if (*dwArg08 != 0x00 && fn00412C40(dwArg08, out edx) <= ~0x03D2)
		{
			fn0041105A(fp - 0x0408, 0x0400, "Stack around the variable '");
			fn00411064(fp - 0x0408, 0x0400, dwArg08);
			fn00411064(fp - 0x0408, 0x0400, "' was corrupted.");
			eax_126 = fp - 0x0408;
		}
		else
			eax_126 = (Eq_2577) &globals->t418338;
		eax_50 = fn00412C60(edx, es, ds, dwArg04, edi_24, 0x02, eax_126, out edx);
	}
	fn004112B2(eax_50, eax_9 ^ fp - 0x04, edx, ebx, esi, edi, es, ds);
	return;
}

// 00412C40: Register word32 fn00412C40(Stack (ptr char) dwArg04, Register out ptr32 edxOut)
word32 fn00412C40(char * dwArg04, ptr32 & edxOut)
{
	word32 edx_7;
	*edxOut = dwArg04;
	char * eax_12 = dwArg04;
	do
	{
		eax_12 = eax_23 + 0x01;
		char * eax_23 = eax_12;
	} while (*eax_23 != 0x00);
	return eax_12 - dwArg04 - 0x01;
}

// 00412C60: Register Eq_254 fn00412C60(Register Eq_51 edx, Register (ptr Eq_56) es, Register (ptr Eq_57) ds, Stack word32 dwArg04, Stack word32 dwArg08, Stack ui32 dwArg0C, Stack Eq_2577 dwArg10, Register out ptr32 edxOut)
Eq_254 fn00412C60(Eq_51 edx, Eq_56 * es, Eq_57 * ds, word32 dwArg04, word32 dwArg08, ui32 dwArg0C, LPCSTR dwArg10, ptr32 & edxOut)
{
	*edxOut = edx;
	ui32 eax_9 = globals->dw41A000 ^ fp - 0x04;
	<anonymous> * dwLoc0E38_32 = null;
	word32 eax_33 = fn004110C8();
	if (eax_33 == 0x00)
		dwLoc0E38_32 = fn00411352();
	ptr32 ebx_357;
	Eq_4011 eax_52 = MultiByteToWideChar(65001, 0x00, dwArg10, ~0x00, null, 0x00);
	if (eax_52 < 0x0200)
	{
		ebx_357 = fp + ~0x0E2F;
		if (MultiByteToWideChar(65001, 0x00, dwArg10, ~0x00, fp + ~0x0E2F, eax_52) != 0x00)
		{
l00412CF5:
			Eq_254 eax_105;
			union Eq_55 * esp_108;
			byte al_104;
			word32 eax_65 = fn00412790(0x1002);
			if (eax_65 != 0x00)
			{
				eax_105 = fn00412850(dwArg0C, globals->a417E44[dwArg0C * 0x04], dwArg04, ebx_357);
				esp_108 = fp - 3660;
				if (eax_105 != 0x00)
					goto l00412E4D;
				al_104 = 0x00;
				eax_105 = DPB(eax_105, 0x00, 0);
			}
			else
			{
				al_104 = 0x01;
				eax_105 = DPB(eax_65, 0x01, 0);
			}
			esp_108 = fp - 3660;
			if (dwLoc0E38_32 != null || eax_33 != 0x00)
			{
				if (al_104 != 0x00)
				{
					eax_105 = IsDebuggerPresent();
					if (eax_105 != 0x00)
						goto l00412E4C;
				}
				word32 esp_182;
				<anonymous> * edi_156;
				word32 edx_157 = fn0041137A(ebx_357, eax_33, es, ds, dwArg04 - 0x05, fp - 0x0210, fp + ~0x0E3B, fp - 0x0418, 0x0104, out edi_156);
				if (edi_156 != null)
				{
					fn0041130C();
					word32 ebp_211;
					byte SCZO_212;
					byte SZO_214;
					byte C_215;
					word32 ebx_216;
					word32 esi_217;
					word32 edi_218;
					byte Z_219;
					byte al_220;
					word32 ecx_221;
					edi_156();
				}
				else
				{
					int32 eax_269 = WideCharToMultiByte(65001, 0x00, fp - 0x0418, ~0x00, fp + ~0x0A2F, 778, null, null);
					fn0041130C();
					word32 ebp_297;
					byte SCZO_298;
					byte SZO_300;
					byte C_301;
					word32 ebx_302;
					word32 esi_303;
					word32 edi_304;
					byte Z_305;
					byte al_306;
					word32 ecx_307;
					dwLoc0E38_32();
				}
				esp_108 = esp_182 + 0x1C;
				if (eax_105 != 0x01)
				{
l00412E4D:
					struct Eq_4067 * esp_88 = (char *) esp_108 + 0x04;
					fn004112B2(eax_105, eax_9 ^ fp - 0x04, edx, esp_88->ptr0004, esp_88->t0000, *esp_108, es, ds);
					return eax_105;
				}
			}
l00412E4C:
			int3();
			goto l00412E4D;
		}
	}
	ebx_357 = 0x00418210;
	goto l00412CF5;
}

// 00413030: Register Eq_254 fn00413030(Stack (ptr Eq_323) dwArg04)
Eq_254 fn00413030(_EXCEPTION_POINTERS * dwArg04)
{
	SetUnhandledExceptionFilter(null);
	UnhandledExceptionFilter(dwArg04);
	return TerminateProcess(GetCurrentProcess(), 0xC0000409);
}

// 00413070: void fn00413070(Register Eq_254 eax, Register ui32 ecx, Register Eq_51 edx, Register (ptr Eq_407) ebx, Register Eq_51 esi, Register Eq_55 edi, Register (ptr Eq_56) es, Register (ptr Eq_57) ds)
void fn00413070(Eq_254 eax, ui32 ecx, Eq_51 edx, Eq_407 * ebx, Eq_51 esi, Eq_55 edi, Eq_56 * es, Eq_57 * ds)
{
	fn00411348();
	if (eax == 0x00)
	{
		globals->t41A250 = eax;
		globals->dw41A24C = ecx;
		globals->t41A248 = edx;
		globals->ptr41A244 = ebx;
		globals->t41A240 = esi;
		globals->t41A23C = edi;
		globals->ptr41A268 = ss;
		globals->ptr41A25C = cs;
		globals->ptr41A238 = ds;
		globals->ptr41A234 = es;
		globals->ptr41A230 = fs;
		globals->ptr41A22C = gs;
		*(fp - 0x0330) = (union Eq_4231 *) false;
		globals->dw41A260 = *(fp - 0x0330);
		globals->dw41A254 = *(fp - 0x04);
		globals->dw41A258 = *fp;
		globals->ptr41A264 = fp + 0x01;
		globals->dw41A1A0 = 0x00010001;
		globals->dw41A15C = globals->dw41A258;
		globals->dw41A150 = 0xC0000409;
		globals->dw41A154 = 0x01;
		globals->dw41A160 = 0x01;
		globals->dw41A164 = 0x02;
		*(fp - 0x0C) = globals->dw41A000;
		*(fp - 0x08) = globals->dw41A004;
		*(fp - 0x0330) = 0x004184E8;
		fn004111F9();
		return;
	}
	else
		__fastfail(0x02);
}

// 004135D0: Register (ptr Eq_4305) fn004135D0(Stack (ptr Eq_3361) dwArg04, Stack uint32 dwArg08)
Eq_4305 * fn004135D0(Eq_3361 * dwArg04, uint32 dwArg08)
{
	struct Eq_4306 * edx_13 = dwArg04 + dwArg04->dw003C / 0x0040;
	struct Eq_4305 * ecx_20 = &edx_13->w0014 + 0x02 + (word32) edx_13->w0014 / 22;
	struct Eq_4305 * ecx_25 = ecx_20 + (word32) edx_13->w0006;
	struct Eq_4305 * dwLoc08_29 = ecx_20;
	while (true)
	{
		struct Eq_4305 * eax_43;
		if (dwLoc08_29 == ecx_25)
			break;
		if (dwArg08 >= dwLoc08_29->dw000C && dwArg08 < dwLoc08_29->dw000C + dwLoc08_29->dw0008)
		{
			eax_43 = dwLoc08_29;
			return eax_43;
		}
		dwLoc08_29 = dwLoc08_29 + 0x01;
	}
	eax_43 = null;
	return eax_43;
}

// 00413690: Register byte fn00413690(Stack (ptr Eq_3352) dwArg04)
byte fn00413690(Eq_3352 * dwArg04)
{
	byte al_18;
	if (dwArg04 == null)
		al_18 = 0x00;
	else if ((word32) dwArg04->w0000 != 23117)
		al_18 = 0x00;
	else
	{
		struct Eq_4356 * ecx_49 = dwArg04 + dwArg04->dw003C / 0x0040;
		if (ecx_49->dw0000 != 0x4550)
			al_18 = 0x00;
		else if ((word32) ecx_49->w0018 != 0x010B)
			al_18 = 0x00;
		else
			al_18 = 0x01;
	}
	return al_18;
}

// 00413920: void fn00413920(Register Eq_51 edx, Register word32 ebx, Register Eq_55 edi, Register (ptr Eq_56) es, Register (ptr Eq_57) ds, Stack word32 dwArg04)
void fn00413920(Eq_51 edx, word32 ebx, Eq_55 edi, Eq_56 * es, Eq_57 * ds, word32 dwArg04)
{
	if (dwArg04 == 0x00)
		globals->b41A53C = 0x01;
	fn00411136(edx, ebx, edi, es, ds);
	fn00411258();
	if (true)
	{
		fn00411023();
		if (false)
		{
			*(fp - 0x08) = 0x00;
			fn00411235();
		}
	}
	return;
}

// 00413DD0: Register ui32 fn00413DD0()
ui32 fn00413DD0()
{
	GetSystemTimeAsFileTime(fp - 0x10);
	ui32 eax_22 = GetCurrentProcessId() ^ (GetCurrentThreadId() ^ 0x00);
	QueryPerformanceCounter(fp - 0x18);
	return eax_22 ^ dwLoc18 ^ dwLoc14 ^ fp - 0x08;
}

// 00413E60: Register ui32 fn00413E60(Register out ptr32 ecxOut, Register out ptr32 edxOut)
ui32 fn00413E60(ptr32 & ecxOut, ptr32 & edxOut)
{
	*edxOut = edx;
	ui32 eax_16;
	if (globals->dw41A000 != 0xBB40E64E)
	{
		ui32 eax_56 = globals->dw41A000;
		eax_16 = eax_56 & 0xFFFF0000;
		if ((eax_56 & 0xFFFF0000) != 0x00)
		{
			word32 ecx_62 = ~globals->dw41A000;
			*ecxOut = ecx_62;
			globals->dw41A004 = ecx_62;
			return eax_16;
		}
	}
	eax_16 = fn00413DD0();
	ui32 dwLoc08_30 = eax_16;
	if (eax_16 == 0xBB40E64E)
		dwLoc08_30 = ~0x44BF19B0;
	else if ((eax_16 & 0xFFFF0000) == 0x00)
	{
		eax_16 = (eax_16 | 0x4711) << 0x10 | eax_16;
		dwLoc08_30 = eax_16;
	}
	globals->dw41A000 = dwLoc08_30;
	word32 edx_41 = ~dwLoc08_30;
	*edxOut = edx_41;
	globals->dw41A004 = edx_41;
	word32 ecx_38;
	*ecxOut = dwLoc08_30;
	return eax_16;
}

// 004143F0: void fn004143F0()
void fn004143F0()
{
	globals->dw41A564 = 0x00;
	return;
}

// 004144E0: Register Eq_254 fn004144E0(Register Eq_51 edx, Register (ptr Eq_407) ebx, Register ptr32 ebp, Register Eq_51 esi, Register Eq_55 edi, Register (ptr Eq_56) es, Register (ptr Eq_57) ds, Register out Eq_2559 edxOut, Register out ptr32 ebxOut)
Eq_254 fn004144E0(Eq_51 edx, Eq_407 * ebx, ptr32 ebp, Eq_51 esi, Eq_55 edi, Eq_56 * es, Eq_57 * ds, Eq_2559 & edxOut, ptr32 & ebxOut)
{
	*edxOut = edx;
	*ebxOut = ebx;
	Eq_254 eax_105;
	ui32 eax_9 = globals->dw41A000 ^ fp - 0x04;
	if (globals->b41A56C != 0x00)
	{
l00414610:
		eax_105.u0 = 0x00;
		goto l00414612;
	}
	globals->b41A56C = 0x01;
	eax_105 = fn00414670(edx, ebx, esi, es, ds, out edx, out edi);
	if (eax_105 == 0x00)
	{
		fn004113C5();
		if (eax_105 == 0x00)
		{
l0041459D:
			*(fp - (****************************************************************************************************) 0x041C) = 0x0A00;
			*(fp - 0x0420) = 0x00;
			*(fp - 0x0424) = 4294572;
			fn004113AC();
			if (eax_105 == 0x00)
			{
				if (GetLastError() != 0x57)
					goto l00414610;
				Mem77[fp - 0x041C + 0x00:word32] = 0x0104;
				Mem80[fp - 0x0420 + 0x00:word32] = fp - 0x0418;
				Mem82[fp - 0x0424 + 0x00:word32] = 0x00;
				fn00411339();
				if ((fp - (****************************************************************************************************) 0x0418 & fp - (****************************************************************************************************) 0x0418) == 0x00)
					goto l00414610;
				Mem88[fp - 0x041C + 0x00:word32] = 0x0104;
				Mem91[fp - 0x0420 + 0x00:word32] = fp - 0x0210;
				Mem94[fp - 0x0424 + 0x00:word32] = fp - 0x0418;
				if (fn00414990(edx, ebx, esi, edi, es, ds, dwArg00, dwArg04, dwArg08) == 0x00)
					goto l00414610;
				Mem104[fp - 0x041C + 0x00:word32] = 0x08;
				Mem107[fp - 0x0420 + 0x00:word32] = 0x00;
				Mem109[fp - 0x0424 + 0x00:word32] = fp - 0x0210;
				fn004113AC();
				eax_105 = fp - (****************************************************************************************************) 0x0210;
				if ((fp - (****************************************************************************************************) 0x0210 & fp - (****************************************************************************************************) 0x0210) == 0x00)
					goto l00414610;
			}
			goto l00414612;
		}
		*(fp - 0x041C) = 0x0104;
		*(fp - 0x0420) = fp - 0x0418;
		*(fp - 0x0424) = (union Eq_254 *) eax_105;
		fn00411339();
		if (eax_105 == 0x00)
			goto l0041459D;
		*(fp - 0x041C) = 0x0104;
		*(fp - 0x0420) = fp - 0x0210;
		*(fp - 0x0424) = fp - 0x0418;
		eax_105 = fn00414990(edx, ebx, esi, edi, es, ds, dwArg00, dwArg04, dwArg08);
		if (eax_105 == 0x00)
			goto l0041459D;
		*(fp - 0x041C) = 0x0900;
		*(fp - 0x0420) = 0x00;
		*(fp - 0x0424) = fp - 0x0210;
		fn004113AC();
		eax_105 = fp - 0x0210;
		if ((fp - 0x0210 & fp - 0x0210) == 0x00)
		{
			eax_105 = GetLastError();
			if (eax_105 != 0x57)
				goto l0041459D;
			Mem153[fp - 0x041C + 0x00:word32] = 0x08;
			Mem156[fp - 0x0420 + 0x00:word32] = 0x00;
			Mem158[fp - 0x0424 + 0x00:word32] = fp - 0x0210;
			fn004113AC();
			eax_105 = fp - (****************************************************************************************************) 0x0210;
			if ((fp - (****************************************************************************************************) 0x0210 & fp - (****************************************************************************************************) 0x0210) == 0x00)
				goto l0041459D;
		}
	}
l00414612:
	fn004112B2(eax_105, eax_9 ^ fp - 0x04, edx, ebx, esi, edi, es, ds);
	return eax_105;
}

// 00414670: Register Eq_254 fn00414670(Register Eq_51 edx, Register (ptr Eq_407) ebx, Register Eq_51 esi, Register (ptr Eq_56) es, Register (ptr Eq_57) ds, Register out ptr32 edxOut, Register out ptr32 ediOut)
Eq_254 fn00414670(Eq_51 edx, Eq_407 * ebx, Eq_51 esi, Eq_56 * es, Eq_57 * ds, ptr32 & edxOut, ptr32 & ediOut)
{
	*edxOut = edx;
	Eq_254 eax_9 = globals->dw41A000 ^ fp - 0x04;
	fn004113AC();
	Eq_254 edi_23 = eax_9;
	if (eax_9 == 0x00)
	{
		fn004113AC();
		edi_23 = eax_9;
		if (eax_9 == 0x00)
		{
			Eq_254 eax_362 = GetLastError();
			if (eax_362 != 0x57)
			{
l004146D7:
				fn004112B2(0x00, eax_9 ^ fp - 0x04, edx, ebx, esi, edi, es, ds);
				word32 edi_370;
				*ediOut = edi;
				return 0x00;
			}
			fn004113AC();
			edi_23 = eax_362;
			if (eax_362 == 0x00)
				goto l004146D7;
		}
	}
	Eq_254 eax_63 = GetProcAddress(edi_23, &globals->t4186A8);
	if (eax_63 != 0x00)
	{
		struct Eq_407 ** esp_116 = fp - 0x022C;
		if (GetProcAddress(edi_23, &globals->t4186B8) != 0x00)
		{
			Eq_254 eax_136 = GetProcAddress(edi_23, &globals->t4186CC);
			esp_116 = fp - 0x022C;
			if (eax_136 != 0x00)
			{
				fn0041130C();
				if (eax_63() != 0x00)
				{
					FreeLibrary(edi_160);
					esp_116 = fp - 0x0240;
				}
				else
				{
					fn0041130C();
					struct Eq_4834 * esp_199;
					word32 ebp_200;
					byte SCZO_201;
					word32 eax_202;
					byte SZO_203;
					byte C_204;
					word32 edi_205;
					byte Z_206;
					word32 ecx_207;
					word32 esi_208;
					word32 ebx_209;
					byte cl_210;
					word32 edx_211;
					word16 si_212;
					word16 cx_213;
					byte CZ_214;
					word16 ax_215;
					struct Eq_4851 * es_216;
					struct Eq_4852 * ds_217;
					ebx_164();
					*(esp_199 - 0x04) = dwLoc0214;
					fn0041130C();
					eax_136();
					*(esp_199 - 0x08) = edi_231;
					FreeLibrary(*(esp_199 - 0x08));
					esp_116 = esp_199 - 0x04;
					if (esi_234 == 0x00 && (dwLoc0220 == 0x01 && true))
					{
						*edxOut = 0x0104;
						if (true)
						{
							uint32 ecx_263 = 0x0103;
							if (wLoc0A == si_238)
							{
								if (wLoc0C != 0x5C)
									ecx_263 = 0x0104;
								if (~ecx_263 >= 0x12 && ecx_263 <= ~0xF2)
								{
									(fp - 0x0210)[ecx_263].dw0000 = globals->dw4185D8;
									(fp - 0x020C)[ecx_263].dw0000 = globals->dw4185DC;
									(fp - 0x0208)[ecx_263].dw0000 = globals->dw4185E0;
									(fp - 0x0204)[ecx_263].dw0000 = globals->dw4185E4;
									(fp - 0x0200)[ecx_263].dw0000 = globals->dw4185E8;
									(fp - 0x01FC)[ecx_263].dw0000 = globals->dw4185EC;
									(fp - 0x01F8)[ecx_263].dw0000 = globals->dw4185F0;
									(fp - 500)[ecx_263].dw0000 = globals->dw4185F4;
									word16 ax_300 = globals->w4185F8;
									*(esp_199 - 0x08) = 0x0900;
									(fp - 0x01F0)[ecx_263] = ax_300;
									*(esp_199 - 0x0C) = 0x00;
									*(esp_199 - 0x10) = fp - 0x0210;
									fn004113AC();
									if ((fp - 0x0210 & fp - 0x0210) == 0x00 && GetLastError() == 0x57)
									{
										*(esp_199 - 0x08) = 0x08;
										*(esp_199 - 0x0C) = (union Eq_5029 *) (fp - 0x0210);
										*(esp_199 - 0x10) = (union Eq_5036 *) (fp - 0x0210);
										fn004113AC();
									}
									Eq_55 edi_327 = esp_199->t0004;
									*ediOut = edi_327;
									fn004112B2(fp - 0x0210, eax_9 ^ fp - 0x04, 0x0104, *(esp_199 - 0x04), esp_199->t0000, edi_327, es, ds);
									return fp - 0x0210;
								}
							}
						}
					}
				}
			}
		}
		struct Eq_4799 * esp_118 = (char *) esp_116 + 0x04;
		Eq_55 edi_123 = esp_118->t0004;
		*ediOut = edi_123;
		fn004112B2(0x00, eax_9 ^ fp - 0x04, edx, *esp_116, esp_118->t0000, edi_123, es, ds);
		return 0x00;
	}
	else
	{
		fn004112B2(eax_63, eax_9 ^ fp - 0x04, edx, ebx, esi, edi, es, ds);
		word32 edi_72;
		*ediOut = edi;
		return eax_63;
	}
}

// 00414990: Register word32 fn00414990(Register Eq_51 edx, Register (ptr Eq_407) ebx, Register Eq_51 esi, Register Eq_55 edi, Register (ptr Eq_56) es, Register (ptr Eq_57) ds, Stack (ptr wchar_t) dwArg04, Stack (ptr wchar_t) dwArg08, Stack Eq_4 dwArg0C)
word32 fn00414990(Eq_51 edx, Eq_407 * ebx, Eq_51 esi, Eq_55 edi, Eq_56 * es, Eq_57 * ds, wchar_t * dwArg04, wchar_t * dwArg08, size_t dwArg0C)
{
	ui32 eax_9 = globals->dw41A000 ^ fp - 0x04;
	if (fn004112DF(dwArg04, fp - 0x10, 0x03, fp - 0x0610, 0x0100, fp - 0x0410, 0x0100, fp - 0x0210, 0x0100) == 0x00 && (fn00411055(fp - 0x0410, 0x09, "M S P D B 1 4 0  ") == 0x00 && fn00411055(fp - 0x0210, 0x04, "D L L  ") == 0x00))
	{
		word32 eax_127 = 0x00 - (-fn0041100A(dwArg08, dwArg0C, fp - 0x10, fp - 0x0610, fp - 0x0410, fp - 0x0210) == 0x00);
		fn004112B2(eax_127 + 0x01, eax_9 ^ fp - 0x04, edx, ebx, esi, edi, es, ds);
		return eax_127 + 0x01;
	}
	else
	{
		fn004112B2(0x00, eax_9 ^ fp - 0x04, edx, ebx, esi, edi, es, ds);
		return 0x00;
	}
}

