// client.c
// Generated by decompiling client.exe
// using Reko decompiler version 0.7.1.0.

#include "client.h"

struct Eq_2865 * g_ptr0000;
Eq_3352 g_t400000 = 
	{
		0x0000,
		0,
	};
Eq_407 g_t411E7C = 
	{
		
		{
			4
		},
		&g_t411E84,
	};
void g_v417B30 = ;
void g_v417CE0 = ;
DWORD g_t417D34 = 0x73654D0A;
word32 g_a417E44[] = 
	{
	};
char g_str417E5C[] = "Stack around the variable '";
char g_str417E78[] = "' was corrupted.";
CHAR g_t418338 = 'S';
word32 g_dw4185D8 = 0x00690062;
word32 g_dw4185DC = 0x005C006E;
word32 g_dw4185E0 = 0x0053004D;
word32 g_dw4185E4 = 0x00440050;
word32 g_dw4185E8 = 0x00310042;
word32 g_dw4185EC = 0x00300034;
word32 g_dw4185F0 = 0x0044002E;
word32 g_dw4185F4 = 0x004C004C;
word16 g_w4185F8 = 0x0000;
CHAR g_t4186A8 = 'R';
CHAR g_t4186B8 = 'R';
CHAR g_t4186CC = 'R';
wchar_t g_str418788[] = "D\x00L\x00L\x00\x00";
wchar_t g_str418794[] = "M\x00S\x00P\x00D\x00B\x001\x004\x000\x00\x00";
CHAR g_t4187C4 = 'P';
ui32 g_dw41A000 = 0xBB40E64E;
word32 g_dw41A004 = 0x44BF19B1;
word32 g_dw41A014 = 0x00000001;
ui32 g_dw41A02C = 0x00000001;
word32 g_dw41A030 = 0x00000001;
word32 g_dw41A150 = 0x00000000;
word32 g_dw41A154 = 0x00000000;
word32 g_dw41A15C = 0x00000000;
word32 g_dw41A160 = 0x00000000;
word32 g_dw41A164 = 0x00000000;
word32 g_dw41A1A0 = 0x00000000;
struct Eq_4228 * g_ptr41A22C = null;
struct Eq_4225 * g_ptr41A230 = null;
struct Eq_56 * g_ptr41A234 = null;
struct Eq_57 * g_ptr41A238 = null;
Eq_55 g_t41A23C = 
	{
		0
	};
Eq_51 g_t41A240 = 
	{
		0
	};
struct Eq_407 * g_ptr41A244 = null;
Eq_51 g_t41A248 = 
	{
		0
	};
ui32 g_dw41A24C = 0x00000000;
Eq_254 g_t41A250 = 
	{
		0
	};
word32 g_dw41A254 = 0x00000000;
word32 g_dw41A258 = 0x00000000;
struct Eq_4218 * g_ptr41A25C = null;
word32 g_dw41A260 = 0x00000000;
ptr32 g_ptr41A264 = 0x00000000;
struct Eq_4215 * g_ptr41A268 = null;
word32 g_dw41A50C = 0x00000000;
word32 g_dw41A510 = 0x00000000;
word32 g_dw41A534 = 0x00000000;
word32 g_dw41A538 = 0x00000000;
byte g_b41A53C = 0x00;
word32 g_dw41A564 = 0x00000000;
Eq_254 g_t41A568 = 
	{
		0
	};
byte g_b41A56C = 0x00;
byte g_b41A56D = 0x00;
word32 g_dw41A570 = 0x00000000;
ui32 g_dw41A574 = 0x00000000;
<anonymous> * g_ptr41C000 = &g_t4112CB;
Eq_2235 g_t411E84 = 
	{
		
		{
		},
		
		{
		},
	};
<anonymous> g_t4112CB = <code>;

